\newcommand*{\standardstate}{{-\kern-6pt{\ominus}\kern-6pt-}}

# Thermochemistry {#Thermochemistry}

## Reaction Enthalpies {#rxnenthalpy}
In chapter \@ref(FirstLaw), we have discussed thermodynamical changes in energy in the absence of chemical reactions. When a chemical reaction takes place, some bonds break and/or some new one form. This process either absorbs or releases the energy contained in these bonds. For a proper thermodynamic treatment of the system, this extra energy must be included in the net balance.

In this chapter, we will consider the heat associated with chemical reactions. Since most chemical reactions happen at constant atmospheric pressure (isobaric conditions) in the lab, we can use eq. \@ref(eq:dh2) to replace the inexact differential of the heat with the exact differential of the state function called enthalpy. The advantage of this transformation is that it allows us to study the heat associated with chemical reactions at constant pressure independently of their path. If we call the molecules at the beginning of the reaction "reactants" and the molecules at the end of the reaction "products," the heat associated with the reaction (rxn) is defined as:

\begin{equation}
  \Delta_{\text{rxn}} H = H_{\text{products}}-H_{\text{reactants}} \; .
  (\#eq:DHrxn1)
\end{equation}

For example, if we take a simple reaction of the form:

$$ \mathrm{A} + \mathrm{B} \rightarrow \mathrm{C} + \mathrm{D}, $$

the heat at constant pressure is equal to the enthalpy of reaction, which is calculated as:

\begin{equation}
  Q_P = \Delta_{\text{rxn}} H = \underbrace{ \left (H_{\mathrm{C}}+H_{\mathrm{D}} \right) }_{\text{products}} - \underbrace{\left( H_{\mathrm{A}}+H_{\mathrm{B}}\right)}_{\text{reactants}}.
  (\#eq:DHrxn2)
\end{equation}

Using the chemistry sign convention, Definition \@ref(def:chemistryconv), reactions are classified in terms of the sign of their reaction enthalpies as follows:

> ```{definition, exoendo} 
$\;$

- $\Delta_{\text{rxn}} H > 0 \Rightarrow$ *Endothermic reaction* (heat is gained by the system).
- $\Delta_{\text{rxn}} H < 0 \Rightarrow$ *Exothermic reaction* (heat is lost by the system).

> ```

If we expand the sample reaction to account for its stoichiometry:

$$ a\mathrm{A} + b\mathrm{B} \rightarrow c\mathrm{C} + d\mathrm{D}\; , $$

where $a,b,c,d$ are the stoichiometric coefficients of species $\mathrm{A,B,C,D}$. Eq. \@ref(eq:DHrxn2) can be rewritten as:

\begin{equation}
  Q_P = \Delta_{\text{rxn}} H = \underbrace{\left( cH_{\mathrm{C}}+dH_{\mathrm{D}} \right) }_{\text{products}} - \underbrace{ \left( aH_{\mathrm{A}}+bH_{\mathrm{B}} \right)}_{\text{reactants}},
  (\#eq:DHrxn3)
\end{equation}

while for the most general case we can write it:

\begin{equation}
  \Delta_{\text{rxn}} H = \sum_i \nu_i H_i,
  (\#eq:DHrxn4)
\end{equation}

where $\nu_i$ is the stoichiometric coefficient of species $i$ with its own sign. The signs of the stoichiometric are defined according to eq. \@ref(eq:DHrxn3) as:

> ```{definition, nui} 
*Signs of the stoichiometric coefficients:*

- $\nu_i$  is **positive** if $i$ is a **product**.
- $\nu_i$  is **negative** if $i$ is a **reactant**.

> ```


## Standard Enthalpies of Formation {#formenthalpy}

In principle, we could use eq. \@ref(eq:DHrxn3) to calculate the reaction enthalpy associated with any reaction. However, to do so, the absolute enthalpies $H_i$ of reactants and products would be required. Unfortunately, absolute enthalpies are not known—and theoretically unknowable, since this would require an absolute zero for the enthalpy scale, which does not exist.^[An example of a known absolute zero for a scale is the zero of the temperature scale, a temperature that can be approached only as a limit from above. No such thing exists for the enthalpy.] To prevent this problem, enthalpies relative to a deﬁned reference state must be used. This reference state is defined at the constituent elements in their standard state, and the enthalpies of 1 mol of substance in this reference state are called **standard enthalpies of formation**.

> ```{definition, stdenthapies}

The *standard enthalpy of formation* of compound $i$, $\Delta_{\mathrm{f}} H_i^\standardstate$, is the change of enthalpy during the formation of 1 mol of $i$ from its constituent elements, with all substances in their standard states. 

> ```

The standard pressure is defined at $P^{\standardstate} = 100 \; \mathrm{kPa} = 1 \; \mathrm{bar}$.^[prior to 1982 the value of $P^{\standardstate} = 1.0 \mathrm{ atm}$ was used. The two values of $P^\standardstate$ are within 1% of each other, since 1 atm = 101.325 kPa.] Strictly speaking, there is no standard temperature, but standard enthalpies of formation are usually reported at room temperature, $T = 298.15 \; \mathrm{K}$. Standard states are indicated with the symbol $\standardstate$ and they are defined for elements as the form in which such element is most stable at standard pressure (for example, for hydrogen, carbon, and oxygen the standard states are $\mathrm{H}_{2(g)}, \mathrm{C}_{(s,\text{graphite})}, \text{and }\mathrm{O}_{2(g)}$,  respectively).^[There are some exception, such as phosphorus, for which the most stable form at 1 bar is black phosphorus, but white phosphorus is chosen as the standard reference state for zero enthalpy of formation. For the purposes of this course, however, we can safely ignore them.]

For example, the standard enthalpies of formation of some common compounds at $T = 298.15 \; \mathrm{K}$ are calculated from the following reactions:

\begin{equation}
\begin{aligned}
  \mathrm{C}_{(s,\text{graphite})}+\mathrm{O}_{2(g)} \rightarrow \mathrm{CO}_{2(g)} \qquad & \Delta_{\mathrm{f}} H_{\mathrm{CO}_{2(g)}}^\standardstate = -394 \; \text{kJ/mol} \\
   \mathrm{C}_{(s,\text{graphite})}+2 \mathrm{H}_{2(g)} \rightarrow \mathrm{CH}_{4(g)} \qquad & \Delta_{\mathrm{f}} H_{\mathrm{CH}_{4(g)}}^\standardstate = -75 \; \text{kJ/mol} \\ 
   \mathrm{H}_{2(g)}+\frac{1}{2} \mathrm{O}_{2(g)} \rightarrow \mathrm{H}_2 \mathrm{O}_{(l)} \qquad & \Delta_{\mathrm{f}} H_{\mathrm{H}_2 \mathrm{O}_{(l)}}^\standardstate = -286 \; \text{kJ/mol} 
\end{aligned}
(\#eq:someDfH)
\end{equation}

A comprehensive list of standard enthalpies of formation of inorganic and organic compounds is also reported in appendix \@ref(appendix).

## Hess's Law {#hessslaw}
The calculation of a standard reaction enthalpy can be performed using the following cycle:

\begin{equation}
\begin{aligned}
 \text{reactants} & \quad \xrightarrow{\Delta_{\text{rxn}} H^\standardstate} \quad \text{products} \\
\scriptstyle{-\Delta_{\text{f}} H_{\text{reactants}}^\standardstate} \quad \bigg\downarrow \quad & \qquad \qquad \qquad \qquad \scriptstyle{\bigg\uparrow  \; \Delta_{\text{f}} H_{\text{products}}^\standardstate} \\
 \text{"elements in } & \text{their standard reference state"}
\end{aligned}
(\#eq:Hesscycle)
\end{equation}

This process is summarized by the simple formula:

\begin{equation}
  \Delta_{\text{rxn}} H^\standardstate = \Delta_{\mathrm{f}} H_{\text{products}}^\standardstate - \Delta_{\mathrm{f}} H_{\text{reactants}}^\standardstate.
  (\#eq:Hess1)
\end{equation}

Notice how there is a negative sign in front of the enthalpy of formation of the reactants because they are normally defined for the reactions that go from the elements to the reactants and not vice-versa. To close the cycle in eq. \@ref(eq:Hesscycle), however, we should go from the reactants to the elements, and therefore we must invert the sign in front of the formation enthalpies of the reactants. Eq. \@ref(eq:Hess1) can be generalized using the same technique used to derive eq. \@ref(eq:DHrxn4), resulting in:

\begin{equation}
  \Delta_{\text{rxn}} H^\standardstate = \sum_i \nu_i \Delta_{\mathrm{f}} H_i^\standardstate,
  (\#eq:Hess)
\end{equation}

which is a mathematical expression of the law that is known as **Hess's Law**. Hess's law is valid at constant pressure because, at those conditions, the heat of reaction—a path function—is equal to the enthalpy of reaction—a state function. Therefore, the enthalpy of a reaction depends exclusively on the initial and final state, and it can be obtained via the pathway that passes through the elements in their standard state (the formation pathway). 

> ```{exercise, HessLawEx}
Calculate the standard enthalpy of formation at 298 K for the combustion of 1 mol of methane, using the data in eq. \@ref(eq:someDfH).

*Solution:* The reaction that is under consideration is:
\begin{equation}
  \mathrm{CH}_{4(g)} + 2 \mathrm{O}_{2(g)} \rightarrow \mathrm{CO}_{2(g)} + 2 \mathrm{H}_2 \mathrm{O}_{(l)} \qquad \Delta_{\mathrm{f}} H_{\mathrm{CH}_{4(g)}}^\standardstate = ?
\end{equation}  

Using Hess's Law, \@ref(eq:Hess), the enthalpy of formation for methane is:
 
\begin{equation}
 \Delta_{\text{rxn}} H^\standardstate =  \Delta_{\text{f}} H^\standardstate_{\mathrm{CO}_{2(g)}} + 2 \Delta_{\text{f}} H^\standardstate_{\mathrm{H}_{2}O_{(l)}} - \Delta_{\text{f}} H^\standardstate_{\mathrm{CH}_{4(g)}} - 2 \underbrace{\Delta_{\text{f}} H^\standardstate_{\mathrm{O}_{2(g)}}}_{=0}
\end{equation}  
 
whose values are reported in eqs. \@ref(eq:someDfH). Notice that the formation enthalpy of $O_{2(g)}$ is zero, since it is an element in its standard state. The final result is:

\begin{equation}
 \Delta_{\text{rxn}} H^\standardstate =  \overbrace{-394}^{\Delta_{\text{f}} H^\standardstate_{\mathrm{CO}_{2(g)}}} +2 \overbrace{(-286)}^{\Delta_{\text{f}} H^\standardstate_{\mathrm{H}_{2}O_{(l)}}} - \overbrace{(-75)}^{\Delta_{\text{f}} H^\standardstate_{\mathrm{CH}_{4(g)}}}  = -891 \mathrm{kJ/mol}.
\end{equation}  

where the negative sign indicates that the reaction is exothermic (see \@ref(def:exoendo)), as we should expect. The cycle that we used to solve this exercise can be summarized with :

\begin{equation}
\begin{aligned}
\mathrm{CH}_{4(g)} + & 2 \mathrm{O}_{2(g)} \quad \xrightarrow{\Delta_{\text{rxn}} H^\standardstate} \quad \mathrm{CO}_{2(g)} + 2 \mathrm{H}_2 \mathrm{O}_{(l)} \\
  \scriptstyle{-\Delta_{\text{f}} H_{\mathrm{CH}_{4(g)},\mathrm{O}_{2(g)}}^\standardstate} & \searrow \qquad \qquad \qquad \qquad \qquad \nearrow \; \scriptstyle{\Delta_{\text{f}} H_{\text{CO}_{2(g)},\mathrm{H}_{2(g)}}^\standardstate}\\
  & \qquad \mathrm{H}_{2(g)}, \mathrm{C}_{(s,\text{graphite})}, \mathrm{O}_{2(g)}
\end{aligned}
\end{equation}

Notice that at standard pressure and $T = 298 \; \mathrm{K}$ water is in liquid form. However, when we burn methane, the heat associated with the exothermic reaction immediately vaporize the water. Substances in different states of matter have different formation enthalpies, and $\Delta_{\text{f}} H^\standardstate_{\mathrm{H}_{2}O_{(l)}} =  -242 \  \mathrm{kJ/mol}$. The difference between the formation enthalpies of the same substance in different states represents the latent heat that separates them. For example, for water:

\begin{equation}
\begin{aligned}
\Delta_{\text{vap}} H^\standardstate_{\mathrm{H}_2O} & = \Delta_{\text{f}} H^\standardstate_{\mathrm{H}_{2}O_{(g)}} - \Delta_{\text{f}} H^\standardstate_{\mathrm{H}_{2}O_{(l)}} \\
& = (-242) - (-286) = + 44 \; \text{kJ/mol}
\end{aligned}
\end{equation}

which is the latent heat of vaporization for water, $\Delta_{\text{vap}} H^\standardstate_{\mathrm{H}_2O}$. The latent heat is positive to indicate that the system absorbs energy in going from the liquid to the gaseous state (and it will release energy when going the opposite direction from gas to liquid).
> ```

## Calculations of Enthalpies of Reaction at $T \neq 298 \; \text{K}$

Standard enthalpies of formation are usually reported at room temperature ($T$ = 298 K), but enthalpies of formation at any temperature $T'$ can be calculated from the values at 298 K using eqs. \@ref(eq:Cpdef) and \@ref(eq:dh2):

\begin{equation}
\begin{aligned}
dH = C_P dT \rightarrow & \int_{H_{T=298}^\standardstate}^{H_{T'}} dH =  \int_{T=298}^{T'} C_P dT \\
            & H_{T'}^\standardstate - H_{T=298}^\standardstate = \int_{T=298}^{T'} C_P dT \\
            & H_{T'}^\standardstate = H_{T=298}^\standardstate + \int_{T=298}^{T'} C_P dT,
\end{aligned}
  (\#eq:DrxnHneq298)
\end{equation}

which, in conjunction with Hess's Law, eq. \@ref(eq:Hess), results in:

\begin{equation}
 \Delta_{\text{rxn}} H_{T'}^\standardstate = \Delta_{\text{rxn}} H_{T=298}^\standardstate + \int_{T=298}^{T'} \Delta C_P dT,
  (\#eq:DrxnHneq298f)
\end{equation}

with $\Delta C_P = \sum_i \nu_i C_{P,i}$.

> ```{exercise, DHtdiff298}
Calculate $\Delta_{\text{rxn}}H$ of the following reaction at 398 K, knowing that $\Delta_{\text{rxn}}H^\standardstate$ at 298 K is -283.0 kJ/mol, and the following $C_P$ values: $\mathrm{CO}_{(g)}$ = 29 J/(mol K), $\mathrm{O}_{2(g)}$ = 30 J/(mol K), $\mathrm{CO}_{2(g)}$ = 38 J/(mol K): 

$$
\mathrm{CO}_{(g)}+\frac{1}{2}\mathrm{O}_{2(g)} \rightarrow \mathrm{CO}_{2(g)},
$$

*Solution:* Using eq. \@ref(eq:DrxnHneq298f) we obtain:

$$
 \Delta_{\text{rxn}} H^{398} = \overbrace{-283.0}^{\Delta_{\text{rxn}}H^\standardstate} + \int_{298}^{398} ( \overbrace{38}^{C_P^{\mathrm{CO}_2}} -\overbrace{29}^{C_P^{\mathrm{CO}}} -\frac{1}{2}\overbrace{30}^{C_P^{\mathrm{O}_2}} ) \times 10^{-3} dT,
$$

which, assuming that the heat capacities does not depend on the temperature, becomes:

\begin{equation}
\begin{aligned}
 \Delta_{\text{rxn}} H^{398} &= -283.0 + \left(38-29-\frac{1}{2}30 \right) \times 10^{-3} (398-298) \\ &= -283.6 \; \text{kJ/mol}.
\end{aligned}
\end{equation}

As we notice from this result, a difference in temperature of 100 K translates into a change in $\Delta_{\text{rxn}}H^\standardstate$ of this reaction of only 0.6 kJ/mol. This is a trend that is often observed, and values of $\Delta_{\text{rxn}}H$ are very weakly dependent on changes in temperature for most chemical reactions. This numerical result can also be compared with the amount that is experimentally measured for $\Delta_{\text{rxn}}H^{398}$ of this reaction, which is –283.67 kJ/mol. This comparison strongly supports the assumption that we used to solve the integral in eq. \@ref(eq:DrxnHneq298f), confirming that the heat capacities are mostly independent of temperature. 

> ```



## Chapter Review {#rev4}

### Practice Problems {#exer4}

**Problem 1:** Calculating $\Delta H$ of a Reaction from Standard Enthalpies of Formation

Determine the enthalpy change, $\Delta_{\text{rxn}} H^\standardstate$, when 1 mole of $\text{N}_2 \text{O}_{4\text{(g)}}$ dissociates into 2 moles of $\text{NO}_{2\text{(g)}}$ at constant standard pressure. Use the standard enthalpy of formation tables at the end of the book to fetch the data that you need.

**Solution:** The reaction under consideration is:

$$\text{N}_2 \text{O}_{4\text{(g)}} \rightarrow 2 \text{NO}_{2\text{(g)}}$$


Using Hess's Law, eq. \@ref(eq:Hess), we get:

$$\Delta_{\text{rxn}} H^\standardstate = 2 \Delta_{\mathrm{f}} H_{\text{NO}_{2\text{(g)}}}^\standardstate -\Delta_{\mathrm{f}} H_{\text{N}_2 \text{O}_{4\text{(g)}}}^\standardstate$$

$$\Delta_{\text{rxn}} H^\standardstate = (2 \times 33.2 \, \text{kJ/mol}) - (11.1 \, \text{kJ/mol}) = 66.4 \, \text{kJ/mol} - 11.1 \, \text{kJ/mol} = 55.3 \, \text{kJ/mol},$$

and, since we are asked to calculate the enhalpy change for 1 mole, we directly get our final answer.

**Answer:**  $\Delta_{\text{rxn}} H^\standardstate = 55.3 \, \text{kJ}$

---

**Problem 2:** Calculating $\Delta H$ of a Reaction from Standard Enthalpies of Formation

Determine the enthalpy change $\Delta_{\text{rxn}} H^\standardstate$ when 1 mole of $\text{SO}_{2\text{(g)}}$ is oxidized to $\text{SO}_{3\text{(g)}}$ at constant standard pressure. Use the standard enthalpy of formation tables at the end of the book to fetch the data that you need.


**Solution:** The reaction under consideration is:
$$2\text{SO}_{2\text{(g)}}+ \text{O}_{2\text{(g)}} \rightarrow 2 \text{SO}_{3\text{(g)}}$$

Using Hess's Law, eq. \@ref(eq:Hess), we get:

$$\Delta_{\text{rxn}} H^\standardstate = 2 \Delta_{\mathrm{f}} H_{\text{SO}_{3\text{(g)}}}^\standardstate - \left(2\Delta_{\mathrm{f}} H_{\text{SO}_{2\text{(g)}}}^\standardstate+\Delta_{\mathrm{f}} H_{\text{O}_{2\text{(g)}}}^\standardstate\right)$$


$$\Delta_{\text{rxn}} H^\standardstate  = \left[2 \times \left(-395.7 \, \text{kJ/mol}\right)\right] - \left[2 \times \left(-296.8 \, \text{kJ/mol}\right) + 0\right]$$

$$\Delta_{\text{rxn}} H^\standardstate  = -791.4 \, \text{kJ/mol} + 593.6 \, \text{kJ/mol} = -197.8 \, \text{kJ/mol}$$

However, we now have to pay attention to the question to provide the right answer, since the question is asking for the reaction enthalpy when 1 mole is oxidized, while the balanced reaction contains 2 moles. 

**Answer:** $\Delta_{\text{rxn}} H^\standardstate = \frac{-197.8 \, \text{kJ/mol}}{2\,\text{mol}} = -98.9 \, \text{kJ}$


### Study Questions {#quest4}

**1. What is the standard enthalpy of formation of a compound?**

a. The change in enthalpy when 1 mole of the compound is formed from its elements in their standard states.
b. The change in enthalpy when 1 mole of the compound is formed from its elements at 273 K.
c. The change in enthalpy when 1 mole of the compound is formed from its elements in the gaseous state.
d. The total energy content of 1 mole of the compound.
e. The amount of heat required to decompose 1 mole of the compound into its elements.

---

**2. Which of the following is true for an exothermic reaction at constant pressure?**

a. $\Delta_{\text{rxn}} H > 0$.
b. $\Delta_{\text{rxn}} H < 0$.
c. $\Delta_{\text{rxn}} H = 0$.
d. The reaction absorbs heat from the surroundings.
e. The reaction releases heat only when carried out in a closed system.

---

**3. What is the relationship between $\Delta_{\text{rxn}} H$ and the stoichiometric coefficients in a reaction?**

a. $\Delta_{\text{rxn}} H$ is independent of stoichiometric coefficients.
b. $\Delta_{\text{rxn}} H$ is directly proportional to the sum of the stoichiometric coefficients.
c. $\Delta_{\text{rxn}} H$ depends on the difference between the stoichiometric coefficients of products and reactants.
d. $\Delta_{\text{rxn}} H$ is directly proportional to the product of the stoichiometric coefficients.
e. $\Delta H_{\text{rxn}}$ is inversely proportional to the stoichiometric coefficients.

---

**4. Which of the following represents Hess's Law?**

a. The total enthalpy change for a reaction is the sum of the enthalpy changes for the individual steps.
b. The enthalpy change of a reaction depends on the pathway taken.
c. The enthalpy change of a reaction is independent of the physical states of reactants and products.
d. The total entropy change for a reaction is the sum of the entropy changes for the individual steps.
e. The enthalpy change for a reaction is equal to the heat absorbed at constant volume.

---

**5. What is the standard enthalpy of formation of $\text{O}_{2\text{(g)}}$ at $298\,\text{K}$?**

a. $0\,\text{kJ/mol}$.
b. $32\,\text{kJ/mol}$.
c. $-286\,\text{kJ/mol}$.
d. $-394\,\text{kJ/mol}$.
e. $75\,\text{kJ/mol}$.

---

**6. What is the enthalpy change associated with the bond dissociation of $\text{Cl}_{2\text{(g)}}$ into two chlorine atoms?**

a. The enthalpy change is negative because energy is released when bonds are broken.
b. The enthalpy change is positive because energy is required to break bonds.
c. The enthalpy change is zero because the process does not involve a chemical reaction.
d. The enthalpy change is negative because $\text{Cl}_{2\text{(g)}}$ is in its standard state.
e. The enthalpy change is undefined because $\text{Cl}_{2\text{(g)}}$ is a diatomic molecule.

---

**7. What is the significance of the latent heat $\Delta H_{\text{vap}}$ of water?**

a. It is the heat required to convert water from solid to liquid.
b. It is the heat released when water condenses from gas to liquid.
c. It is the heat required to convert water from liquid to gas.
d. It is the heat required to heat water from $273\,\text{K}$ to $373 \,\text{K}$.
e. It is the heat released when water freezes from liquid to solid.

---

**8. Which of the following statements is true regarding the calculation of enthalpies of reaction at temperatures different from $298\,\text{K}$**

a. The enthalpy of reaction remains constant with temperature.
b. The enthalpy of reaction is independent of the specific heat capacities of reactants and products.
c. The enthalpy of reaction can be calculated using heat capacities and temperature changes.
d. The enthalpy of reaction decreases linearly with temperature.
e. The enthalpy of reaction cannot be calculated for temperatures different from $298\,\text{K}$.

---

**9. Which of the following is true about the standard state of a substance?**

a. The standard state of a substance is always at $273\,\text{K}$ and $1\,\text{bar}$ pressure.
b. The standard state of a substance is the gas phase at $1\,\text{bar}$ pressure and $298 \,\text{K}$.
c. The standard state of a substance is defined only for elements, not for compounds.
d. The standard state of a substance is its liquid form at $1\,\text{bar}$ pressure and $298\,\text{K}$.
e. The standard state of a substance is the most stable form of the substance at $1\,\text{bar}$ pressure and a specified temperature, usually $298 \,\text{K}$.

---

**10. According to Hess's Law, what is a reaction where the sum of the enthalpies of the products is greater than that of the reactants?**

a. The reaction is endothermic.
b. The reaction is exothermic.
c. The reaction is spontaneous.
d. The reaction is non-spontaneous.
e. The reaction does not occur.

---

`r if (knitr::is_html_output()) {
  '
  Answers: <span style="cursor: pointer; color: blue; text-decoration: underline;" onclick="document.getElementById(\'reveal-inline-content\').style.display=\'inline\'; this.style.display=\'none\';">
    Click to reveal
  </span>
  <span id="reveal-inline-content" style="display: none;">
1.a, 2.b, 3.c, 4.a, 5.a, 6.b, 7.c, 8.c, 9.e, 10.a
  </span>
  '
} else if (knitr::is_latex_output()) {
  'Answers: 1.a, 2.b, 3.c, 4.a, 5.a, 6.b, 7.c, 8.c, 9.e, 10.a
'
}`
