\renewcommand*{\standardstate}{{-\kern-6pt{\ominus}\kern-6pt-}}

# Chemical Equilibrium {#ChemicalEquilibrium}

## Reaction Quotient and Equilibrium Constant
Let's consider a prototypical reaction at constant $T,P$:

\begin{equation}
 a\mathrm{A} + b\mathrm{B} \rightarrow c\mathrm{C} + d\mathrm{D} 
(\#eq:reaction4)
\end{equation}

The Gibbs free energy of the reaction is defined as:

\begin{equation}
\Delta_{\text{rxn}} G = G_{\text{products}} - G_{\text{reactants}} = G^{\text{C}} + G^{\text{D}} - G^{\text{A}}-G^{\text{B}},
(\#eq:chemeq1)
\end{equation}

and replacing the absolute Gibbs free energies with the chemical potentials $\mu_i$, we obtain:

\begin{equation}
\Delta_{\text{rxn}} G = c \mu_{\text{C}} + d \mu_{\text{D}} - a \mu_{\text{A}}- b\mu_{\text{B}}.
(\#eq:chemeq2)
\end{equation}

Assuming the reaction is happening in the gas phase, we can then use eq. \@ref(eq:dgconstn5) to replace the chemical potentials with their value in the reaction mixture, as:

\begin{equation}
\begin{aligned}
\mkern-60mu \Delta_{\text{rxn}} G =& \; c (\mu_{\text{C}}^\standardstate +RT \ln P_{\text{C}}) + d (\mu_{\text{D}}^\standardstate +RT \ln P_{\text{D}}) +\\ & - a (\mu_{\text{A}}^\standardstate +RT \ln P_{\text{A}}) - b (\mu_{\text{B}}^\standardstate +RT \ln P_{\text{B}}) \\
  =& \; \underbrace{c \mu_{\text{C}}^\standardstate + d \mu_{\text{D}}^\standardstate - a \mu_{\text{A}}^\standardstate - b\mu_{\text{B}}^\standardstate}_{\Delta_{\text{rxn}} G^\standardstate}  +RT \ln \frac{P_{\text{C}}^c \cdot P_{\text{D}}^d}{P_{\text{A}}^a \cdot P_{\text{B}}^b}.
\end{aligned}
(\#eq:chemeq3)
\end{equation}

We can define a new quantity called the *reaction quotient* as a function of the partial pressures of each substance:^[Notice that since we used eq. \@ref(eq:dgconstn4) to derive the reaction quotient, the partial pressures inside it are always dimensionless since they are divided by $P^\standardstate$.]

\begin{equation}
Q_P = \frac{P_{\text{C}}^c \cdot P_{\text{D}}^d}{P_{\text{A}}^a \cdot P_{\text{B}}^b},
(\#eq:chemeq4)
\end{equation}

and we can then simply rewrite eq. \@ref(eq:chemeq3) using eq. \@ref(eq:chemeq4) as:

\begin{equation}
\Delta_{\text{rxn}} G = \Delta_{\text{rxn}} G^\standardstate + RT \ln Q_P.
(\#eq:chemeq5)
\end{equation}

This equation tells us that the sign of $\Delta_{\text{rxn}} G$ is influenced by the reaction quotient $Q_P$. For a spontaneous reaction at the beginning, the partial pressures of the reactants are much higher than the partial pressures of the porducts, therefore $Q_P \ll 1$ and $\Delta_{\text{rxn}} G < 0$, as we expect. As the reaction proceeds, the partial pressures of the products will increase, while the partial pressures of the reactants will decrease. Consequently, both $Q_P$ and $\Delta_{\text{rxn}} G$ will increase. The reaction will completely stop when $\Delta_{\text{rxn}} G = 0$, which is the chemical equilibrium point. At the reaction equilibrium:

\begin{equation}
\Delta_{\text{rxn}} G = 0 = \Delta_{\text{rxn}} G^\standardstate + RT \ln K_P,
(\#eq:chemeq6)
\end{equation}

where we have defined a new quantity called **equilibrium constant**, as the value the reaction quotient assumes when the reaction reaches equilibrium, and we have denoted it with the symbol $K_P$.^[The subscript $P$ refers to the fact that the equilibrium constant is measured in terms of partial pressures.] From eq. \@ref(eq:chemeq6) we can derive the following fundamental equation on the standard Gibbs free energy of reaction:

\begin{equation}
\Delta_{\text{rxn}} G^\standardstate = - RT \ln K_P.
(\#eq:chemeqdg0)
\end{equation}

To extend the concept of $K_P$ beyond the four species in the prototypical reaction \@ref(eq:reaction4), we can use the product of a series symbol $\left( \prod_i \right)$, and write:

\begin{equation}
K_P=\prod_i P_{i,\text{eq}}^{\nu_i},
(\#eq:kpdef)
\end{equation}

where $P_{i,\text{eq}}$ are the partial pressure of each species at equilibrium. Eq. \@ref(eq:kpdef) is in principle valid for ideal gases only. However, reaction involving ideal gases are pretty rare. As such, we can further extend the concept of equilibrium constant and write:

\begin{equation}
K_{\text{eq}} =\prod_i a_{i,\text{eq}}^{\nu_i},
(\#eq:kdef)
\end{equation}

where we have replaced the partial pressure at equilibrium, $P_{i,\text{eq}}$, with a new concept introduced initially by Gilbert Newton Lewis (1875–1946),^[Gilber Lewis is the same scientist that invented the concept of Lewis Structures.] that he termed **activiy**, and represented by the letter $a$. For ideal gases, it is clear that $a_i=P_i/P^\standardstate$. For non-ideal gases, the activity is equal to the fugacity $a_i=f_i/P^\standardstate$, a concept that we will investigate in the next chapter. For pure liquids and solids, the activity is simply $a_i=1$. For diluted solutions, the activity is equal to a measured concentration (such as, for example, the mole fraction $x_i$ in the liquid phase, and $y_i$ in the gas phase, or the molar concentration $[i]/[i]^\standardstate$ with $[i]^\standardstate = 1\;\text[mol/L]$). Finally for concentrated solutions, the activity is related to the measured concentration via an activity coefficient. We will return to the concept of activity in chapter \@ref(Solutions), when we will specifically deal with solutions. For now, it is interesting to use the activity to write the definition of the following two constants:

\begin{equation}
K_y =\prod_i \left( y_{i,\text{eq}} \right)^{\nu_i} \qquad \qquad \qquad \qquad K_C =\left( \prod_i [i]_{\text{eq}}/[i]^\standardstate \right)^{\nu_i},
(\#eq:kxkcdef)
\end{equation}

which can then be related with $K_P$ for a mixture of ideal gases using:

\begin{equation}
P_i = y_i P \qquad \qquad \qquad P_i=\frac{n_i}{V}RT=[i]RT,
(\#eq:kxkcdef2)
\end{equation}

which then results in:

\begin{equation}
K_P = K_y\cdot \left(\frac{P}{P^\standardstate}\right)^{\Delta \nu} \qquad \qquad K_P = K_C \left( \frac{[i]^\standardstate RT}{P^\standardstate} \right)^{\Delta \nu},
(\#eq:kxkcdef3)
\end{equation}

with $\Delta \nu =\sum_i \nu_i$. 

Using the general equilibrium constant, $K_{\text{eq}}$, we can also rewrite the fundamental equation on $\Delta_{\text{rxn}} G^\standardstate$ that we derived in eq. \@ref(eq:chemeqdg0) to be applicable at most conditions, as:

\begin{equation}
\Delta_{\text{rxn}} G^\standardstate = - RT \ln K_{\text{eq}},
(\#eq:chemeqdgG)
\end{equation}

and since $\Delta_{\text{rxn}} G^\standardstate$ depends on $T,P$ and $\{n_i\}$, it is useful to explore how $K_{\text{eq}}$ depends on those variables as well.

## Temperature Dependence of $K_{\text{eq}}$

To study the temperature dependence of $K_{\text{eq}}$ we can use eq. \@ref(eq:chemeqdgG) for the general equilibrium constant and write:

\begin{equation}
\ln K_{\text{eq}} = -\frac{\Delta G^\standardstate}{RT},
(\#eq:kptemp1)
\end{equation}

which we can then differentiate with respect to $dT$ at constant $P,\{n_i\}$ on both sides:

\begin{equation}
\left( \frac{\partial \ln K_{\text{eq}}}{\partial T} \right)_{P,\{n_i\}} = -\frac{1}{R} \left[ \partial \left( \frac{\partial \frac{\Delta F^\standardstate}{RT}}{\partial T} \right) \right]_{P,\{n_i\}},
(\#eq:kptemp2)
\end{equation}

and, using Gibbs-Helmholtz equation (eq. \@ref(eq:gibbshelm)) to simplify the left hand side, becomes:

\begin{equation}
\left( \frac{\partial \ln K_{\text{eq}}}{\partial T} \right)_{P,\{n_i\}} = -\frac{1}{R} \left( -\frac{\Delta H^\standardstate}{T^2} \right) = \frac{\Delta H^\standardstate}{RT^2},
(\#eq:kptemp3)
\end{equation}

which gives the dependence of $\ln K_{\text{eq}}$ on $T$ that we were looking for. Eq. \@ref(eq:kptemp3) is also called **van 't Hoff equation**,^[named after Jacobus Henricus "Henry" van 't Hoff Jr. (1852–1911).] and it is the mathematical expression of Le Chatelier's principle. The simplest interpretation is as follows:

- For an exothermic reaction ($\Delta H^\standardstate < 0$): $K_{\text{eq}}$ will decrease as the temperature increases. 
- For an endothermic reaction ($\Delta H^\standardstate > 0$): $K_{\text{eq}}$ will increase as the temperature increases. 

If we integrate the van 't Hoff equation between two arbitrary points at constant $P$, and assuming constant $\Delta H^\standardstate$, we obtain the following:

\begin{equation}
\int_1^2 d \ln K_{\text{eq}} = \frac{\Delta H^\standardstate}{R} \int_1^2 \frac{dT}{T^2},
(\#eq:kptemp4)
\end{equation}

which leads to the linear equation:

\begin{equation}
\ln K_{\text{eq}}(2) = \ln K_{\text{eq}}(1) - \frac{\Delta H^\standardstate}{R} \left( \frac{1}{T_2}-\frac{1}{T_1} \right).
(\#eq:vthoffeqI)
\end{equation}

which is the equation that produces the so-called **van 't Hoff plots**, from which $\Delta H^\standardstate$ can be experimentally determined:

```{r vthoffplt, echo=FALSE, fig.align='center', fig.cap='Van \'t Hoff Plots for an Endothermic (Left, Blue) and an Exothermic (Right, Red) Reactions at Constant P.'}
x <- seq(0.2,0.8,0.01)
i <- 0.2
f <- 1
p1 <- 0.5
old.par <- par(mfrow=c(1, 2))
par(pty="s")
par(mar=c(0,2,0,2))
plot(x, 90-90*x,
     xlim=c(0.2, 0.8),
     ylim=c(0, 100),
     type="l",
     xaxt='n',
     yaxt='n',
     mgp=c(0.5,0.5,0),
     ylab = "ln K", xlab = "1/T", col = "#2E9FDF")
arrows(0.3 , 35, 0.65, 35 , length=0, angle=90, code=3, lty="dotted")
points(0.25,90-90*0.25, col="black", pch=19)
points(0.75,90-90*0.75, col="black", pch=19)
text(0.28,90-90*0.25+5, "1", col="black")
text(0.78,90-90*0.75+5, "2", col="black")
text(0.4,42, expression(paste(-Delta, H^o,"/T")), col = "black")
legend("topright", inset=.02, "Endothermic",, bg = "white", adj=0.15, box.col = "white")

par(mar=c(0,2,0,2))
plot(x, 10+90*x,
     xlim=c(0.2, 0.8),
     ylim=c(0, 100),
     type="l",
     xaxt='n',
     yaxt='n',
     mgp=c(0.5,0.5,0),
     ylab = "ln K", xlab = "1/T", col = "red")
arrows(0.3 , 40, 0.65, 40 , length=0, angle=90, code=3, lty="dotted")
points(0.25,10+90*0.25, col="black", pch=19)
points(0.75,10+90*0.75, col="black", pch=19)
text(0.23,10+90*0.25+5, "1", col="black")
text(0.73,10+90*0.75+5, "2", col="black")
text(0.5,47, expression(paste(-Delta, H^o,"/T")), col = "black")
legend("topright", inset=.02, "Exothermic",, bg = "white", adj=0.15, box.col = "white")
par(old.par)
```


## Pressure and Composition Dependence of $K_{\text{eq}}$

While $K_P$ is independent of both temperature and number of moles for an ideal gas, the same is not necessarily true for the other equilibrium constants. 

\begin{equation}
\left( \frac{\partial K_P}{\partial P} \right)_{T,\{n_i\}} = 0 \qquad \qquad \left( \frac{\partial K_P}{\partial n_i}=0 \right)_{T,P}.
(\#eq:kppni)
\end{equation}

For example, it is easy to look at eq. \@ref(eq:kxkcdef3) and determine that $K_y$ usually depends on $P$.^[$K_y$  becomes independent of $P$ in the particular case where $\Delta \nu=0$, i.e., for reactions where the total number of moles of reactants is the same as the total number of moles of the products.] Using Dalton's Law, eq. \@ref(eq:daltonlaw), we can also notice that the equilibrium partial pressures of the reactants and products in a gas-phase reaction can be expressed in terms of their equilibrium mole fractions $y_i$ and the total pressure $P$. As such, we can use $K_y$ to demonstrate that the equilibrium mole fractions will change when $P$ changes,^[Keep in mind that $K_P$ will *not* change.] as it is demonstrated by the following exercise.

> ```{exercise, kpkx}
Calculate the mole fraction change for the dissociation of $\mathrm{Cl}_{2(g)}$ when the pressure is increased from $P^\standardstate$ to $P_f=2.5 \;\text{bar}$ at constant $T=2\,298\;\mathrm{K}$, knowing that $\Delta_{\mathrm{f}} G^\standardstate_{\mathrm{Cl}_{(g)}} = 105.3 \;\text{kJ/mol}$ and $\Delta_{\mathrm{f}} H^\standardstate_{\mathrm{Cl}_{(g)}} = 121.3 \;\text{kJ/mol}$, and remembering that both of these values are tabulated at $T=298\;\text{K}$.

*Solution:* Let's consider the reaction:
$$
\mathrm{Cl}_{2(g)} \rightleftarrows 2 \mathrm{Cl}_{(g)}
$$

We can divide the exercise into two parts. In the first one, we will deal with calculating the equilibrium constant at $T=2\,298\;\mathrm{K}$ from the data at $T=298\;\mathrm{K}$. In the second one, we will calculate the change in mole fraction when the pressure is increased from $P^\standardstate=1\;\text{bar}$ to $P_f=2.5 \;\text{bar}$. 

- Let's begin the first part by calculating $\Delta_{\text{rxn}} G^\standardstate$ and $\Delta_{\text{rxn}} H^\standardstate$ from:
\begin{equation}
\begin{aligned}
\Delta_{\text{rxn}} G^\standardstate &= 2 \Delta_{\text{f}} G^\standardstate_{\text{Cl}_{(g)}} - \Delta_{\text{f}} G^\standardstate_{\text{Cl}_{2(g)}} \\
\Delta_{\text{rxn}} H^\standardstate &= 2 \Delta_{\text{f}} H^\standardstate_{\text{Cl}_{(g)}} - \Delta_{\text{f}} H^\standardstate_{\text{Cl}_{2(g)}},
\end{aligned}
\end{equation}
and since $\text{Cl}_{2(g)}$ is an element in its most stable form at $T=298\;\mathrm{K}$, its standard enthalpy and Gibbs free energy of formation are $\Delta_{\text{f}} H^\standardstate_{\text{Cl}_{2(g)}} = \Delta_{\text{f}} G^\standardstate_{\text{Cl}_{2(g)}} = 0$. Therefore:^[Notice how a positive $\Delta_{\text{rxn}} G^\standardstate$ indicates that the dissociation of $\mathrm{CL}_{2(g)}$ is non-spontaneous at $T=298\;\text{K}$ and $P=1\;\text{bar}$. As such, we should expect a very small value for $K_P$.]
\begin{equation}
\begin{aligned}
\Delta_{\text{rxn}} G^\standardstate &= 2 \cdot 105.3 - 0 = 210.6 \;\text{kJ/mol} \\
\Delta_{\text{rxn}} H^\standardstate &= 2 \cdot 121.3 - 0 = 242.6\;\text{kJ/mol}.
\end{aligned}
\end{equation}
Using eq. \@ref(eq:chemeqdg0) to calculate $K_P (P^\standardstate,298\;\text{K})$, we obtain:^[The results corresponds to $K_P=1.2\times 10^{-37}$, an incredible miniscule number, as we should expect given the data of $\Delta_{\text{rxn}} G^\standardstate$.]
\begin{equation}
\ln [ K_P (P^\standardstate,298\;\text{K}) ] =  \frac{ - \Delta_{\text{rxn}} G^\standardstate}{RT}  =  \frac{-210.6\times10^3}{8.31 \cdot 298} = - 85.0.
\end{equation}
We can now use the integrated van 't Hoff equation, eq. \@ref(eq:vthoffeqI), to calculate $K_P$ at $T=2\,298\;\text{K}$:
\begin{equation}
\begin{aligned}
\ln [K_P (P^\standardstate,&2\,298\;\text{K})] = \ln [K_P (P^\standardstate,298\;\text{K})] \;+ \\ &-\frac{\Delta_{\text{rxn}} H^\standardstate}{R} \left(\frac{1}{2\,298}-\frac{1}{298} \right),
\end{aligned}
\end{equation}
which becomes:
\begin{equation}
\begin{aligned}
\ln [K_P (P^\standardstate,&2\,298\;\text{K})] = - 85.0 \;+\\&-\frac{242.6\times 10^{3}}{8.31} \left(\frac{1}{2\,298}-\frac{1}{298} \right) = 0.262\;,
\end{aligned}
\end{equation}
which corresponds to:
\begin{equation}
K_P (P^\standardstate,2\,298\;\text{K}) = \exp (0.262)=1.30.
\end{equation}

- Let's now move to the second part of the exercise, where we increase the pressure from $1\;\text{bar}$ to $2.5\;\text{bar}$ at constant $T=2\,298\;\text{K}$. We start by writing the definition of $K_P$ and $K_y$:
\begin{equation}
K_P=\frac{P_\mathrm{Cl_{(g)}}^2}{P_{\mathrm{Cl}_{2(g)}}} \qquad \qquad  K_y=\frac{y_\mathrm{Cl_{(g)}}^2}{y_{\mathrm{Cl}_{2(g)}}},
\end{equation}
and using eq. \@ref(eq:kxkcdef3):
\begin{equation}
\begin{aligned}
\Delta \nu &= 2 - 1 = 1 \\
K_P &= K_y \cdot \frac{P}{P^\standardstate} \quad \xrightarrow \qquad K_y=K_P \left( \frac{P}{P^\standardstate} \right)^{-1},
\end{aligned}
\end{equation}
we can calculate the initial $K_y$ at $P_i=P^\standardstate$, using:
\begin{equation}
K_y (P^\standardstate,2\,298\;\text{K}) = 1.30 =\frac{1.30}{1}.
\end{equation}
and calculate the initial concentration of $\mathrm{Cl}_{(g)}$ and $\mathrm{Cl}_{(g)}$ at $P^\standardstate$, recalling that $y_{\mathrm{Cl}_{2(g)}}=1-y_{\mathrm{Cl}_{(g)}}:$
\begin{equation}
K_y (P_i,2\,298\;\text{K})=\frac{\left(y^i_{\mathrm{Cl}_{(g)}}\right)^2}{y^i_{\mathrm{Cl}_{(g)}}} = 1.30.
\end{equation}
Solving the quadratic equation, we obtain one negative answer—which is unphysical—,^[Concentration cannot be negative.] and:
\begin{equation}
y_{\mathrm{Cl}_{(g)}}^i= 0.662 \quad \xrightarrow \qquad y_{\mathrm{Cl}_{2(g)}}^i=1-0.662 = 0.338.
\end{equation}
At the end of the process, $P_f=2.5\;\text{bar}$, and we obtain:
\begin{equation}
K_y (P_f,2\,298\;\text{K}) = 0.520 = K_P \frac{P^\standardstate}{P_f} = \frac{1.30}{2.5},
\end{equation}
and, using the same technique used before to solve the quadratic equation:
\begin{equation}
K_y (P_f,2\,298\;\text{K})=\frac{\left(y^f_{\mathrm{Cl}_{(g)}}\right)^2}{y^f_{\mathrm{Cl}_{(g)}}} = 0.520,
\end{equation}
gives:
\begin{equation}
y_{\mathrm{Cl}_{(g)}}^f=0.507 \quad \xrightarrow \qquad y_{\mathrm{Cl}_{2(g)}}^i=1-0.507 = 0.493.
\end{equation}
To summarize, when we increase the pressure from $1\;\text{bar}$ to $2.5\;\text{bar}$ at $T=2\,298\;\text{K}$, the equilibrium constant in terms of the mole fraction decreases from $K_y(P^\standardstate,2\,298\;\text{K})=1.30$ to $K_y(P_f=2.5\;\text{bar},2\,298\;\text{K})=0.520$. This reduction is causing a shift of the equilibrium towards the reactants, with the concentration of  $\text{Cl}_{2(g)}$ increasing from $y_{\text{Cl}_{2(g)}}^i = 0.338$ to $y_{\text{Cl}_{2(g)}}^f = 0.493$ and the concentration of $\text{Cl}_{(g)}$ decreasing from $y_{\text{Cl}_{2(g)}}^i = 0.662$ to $y_{\text{Cl}_{(g)}}^f = 0.507$.

```

The dependence of $K_{\text{eq}}$ on $P$ highlighted above is another mathematical expression of Le Chatelier's principle, on this occasion, for changes in pressure. The interpretation For a reaction happening in the gas phase is as follows:

- If the total pressure increases, the equilibrium will shift towards the side of the chemical equation that contains the smallest total amount of moles (the equilibrium in exercise \@ref(exr:kpkx) shifts toward the reactant).

